using System.Text;

namespace ToggleMesh.CLI.Generators;

public class CSharpGenerator : ICodeGenerator
{
    public string LanguageName => "csharp";
    public string DefaultFileName => "ToggleMeshFlags.g.cs";

    public string Generate(Dictionary<string, string> mappedKeys)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This file was generated by ToggleMesh CLI.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("namespace ToggleMesh.Generated;");
        sb.AppendLine();
        sb.AppendLine("public static class Flags");
        sb.AppendLine("{");
        foreach (var kvp in mappedKeys)
            sb.AppendLine($"    public const string {kvp.Key} = \"{kvp.Value}\";");
        sb.AppendLine("}");
        return sb.ToString();
    }
}