using System.Text;

namespace ToggleMesh.CLI.Generators;

public class GoGenerator : ICodeGenerator
{
    public string LanguageName => "go";
    public string DefaultFileName => "flags.go";

    public string Generate(Dictionary<string, string> mappedKeys)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This file was generated by ToggleMesh CLI.");
        sb.AppendLine("// Do not edit this file manually.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("package togglemesh");
        sb.AppendLine();
        sb.AppendLine("const (");
        foreach (var kvp in mappedKeys)
            sb.AppendLine($"\t{kvp.Key} = \"{kvp.Value}\"");
        sb.AppendLine(")");
        return sb.ToString();
    }
}