using System.Text;

namespace ToggleMesh.CLI.Generators;

public class JavaScriptGenerator : ICodeGenerator
{
    public string LanguageName => "javascript";
    public string DefaultFileName => "togglemesh-flags.js";

    public string Generate(Dictionary<string, string> mappedKeys)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This file was generated by ToggleMesh CLI.");
        sb.AppendLine("// Do not edit this file manually.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("export const Flags = {");
        foreach (var kvp in mappedKeys)
            sb.AppendLine($"  {kvp.Key}: '{kvp.Value}',");
        sb.AppendLine("};");
        return sb.ToString();
    }
}