using System.Text;

namespace ToggleMesh.CLI.Generators;

public class PythonGenerator : ICodeGenerator
{
    public string LanguageName => "python";
    public string DefaultFileName => "togglemesh_flags.py";

    public string Generate(Dictionary<string, string> mappedKeys)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# <auto-generated>");
        sb.AppendLine("# This file was generated by ToggleMesh CLI.");
        sb.AppendLine("# Do not edit this file manually.");
        sb.AppendLine("# </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("class Flags:");
        foreach (var kvp in mappedKeys)
            sb.AppendLine($"    {kvp.Key} = \"{kvp.Value}\"");
        return sb.ToString();
    }
}
