using System.Text;

namespace ToggleMesh.CLI.Generators;

public class TypeScriptGenerator : ICodeGenerator
{
    public string LanguageName => "typescript";
    public string DefaultFileName => "togglemesh-flags.ts";

    public string Generate(Dictionary<string, string> mappedKeys)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// @ts-nocheck");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This file was generated by ToggleMesh CLI.");
        sb.AppendLine("// Do not edit this file manually.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("export const Flags = {");
        foreach (var kvp in mappedKeys)
            sb.AppendLine($"  {kvp.Key}: '{kvp.Value}',");
        sb.AppendLine("} as const;\n");
        sb.AppendLine("export type FlagKey = typeof Flags[keyof typeof Flags];");
        return sb.ToString();
    }
}