services:
  db:
    image: postgres:latest
    container_name: togglemesh-db
    environment:
      POSTGRES_DB: togglemesh
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: togglemesh-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    container_name: togglemesh-clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: togglemesh
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./docker/clickhouse:/docker-entrypoint-initdb.d

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: togglemesh-kafka
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    restart: unless-stopped
    volumes:
      - kafka_data:/var/lib/kafka/data

volumes:
  postgres_data:
  clickhouse_data:
  kafka_data: