namespace ToggleMesh.Common.Rules;

/// <summary>
/// Defines a custom rule operator for the ToggleMesh evaluation engine.
/// Implementations must be thread-safe as they are registered as Singletons.
/// </summary>
public interface IRuleOperator
{
    /// <summary>
    /// The unique identifier of the operator. 
    /// This must match the operator key sent from the ToggleMesh Control Plane.
    /// Example: "Equals", "GreaterThan", "InList", "Regex".
    /// </summary>
    string Name { get; }

    /// <summary>
    /// Pre-compiles or parses the raw string rule value into a typed, optimized object.
    /// This method is called once when flags are synchronized or updated (Cold Path).
    /// </summary>
    /// <param name="ruleValue">The raw string value from the configuration (e.g., "v1.2.0" or "user@company.com").</param>
    /// <returns>
    /// A compiled object (e.g., Regex, NuGetVersion, HashSet, or double) to be used during evaluation.
    /// This object will be passed directly to the <see cref="Evaluate"/> method.
    /// </returns>
    object? Compile(string ruleValue);

    /// <summary>
    /// Evaluates whether the user's attribute satisfies the rule criteria.
    /// This method is executed on every flag check (Hot Path) and must be highly optimized with zero heap allocations.
    /// </summary>
    /// <param name="userValue">The attribute value provided in the User Context.</param>
    /// <param name="compiledRuleValue">
    /// The pre-compiled object generated by the <see cref="Compile"/> method. 
    /// The implementation should cast this to the expected type.
    /// </param>
    /// <returns>True if the condition is met; otherwise, false.</returns>
    bool Evaluate(string userValue, object? compiledRuleValue);
}