// <auto-generated>
// This file was generated by ToggleMesh Go CLI.
// Do not edit this file manually.
// </auto-generated>

package main

const (
	VideoProductReviews = "video_product_reviews"
	Gmail20percent = "gmail-20percent"
	Gmail21percent = "gmail-21percent"
)
