// <auto-generated>
// This file was generated by ToggleMesh CLI.
// </auto-generated>

namespace ToggleMesh.Generated;

public static class Flags
{
    public const string Gmail20percent = "gmail-20percent";
}
