using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ToggleMesh.SDK.Generators.Contexts;

[Generator]
public class ContextAccessorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is TypeDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null);

        var compilationAndTypes = context.CompilationProvider.Combine(provider.Collect());

        context.RegisterSourceOutput(compilationAndTypes,
            static (spc, source) => Execute(source.Left, source.Right, spc));
    }

    private static TypeDeclarationSyntax? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var typeDeclaration = (TypeDeclarationSyntax)context.Node;
            
        foreach (var attributeListSyntax in typeDeclaration.AttributeLists)
        foreach (var attributeSyntax in attributeListSyntax.Attributes)
        {
            var symbol = context.SemanticModel.GetSymbolInfo(attributeSyntax).Symbol;
            if (symbol is not IMethodSymbol methodSymbol) 
                continue;
                    
            var fullName = methodSymbol.ContainingType.ToDisplayString();
            if (fullName == "ToggleMesh.SDK.Attributes.ToggleMeshContextAttribute")
                return typeDeclaration;
        }
            
        return null;
    }

    private static void Execute(Compilation compilation, IEnumerable<TypeDeclarationSyntax?> types, SourceProductionContext context)
    {
        var typeDeclarationSyntaxes = types.ToList();
        if (!typeDeclarationSyntaxes.Any())
            return;

        foreach (var typeSyntax in typeDeclarationSyntaxes.Distinct())
        {
            if (typeSyntax is null) continue;

            var semanticModel = compilation.GetSemanticModel(typeSyntax.SyntaxTree);
            if (semanticModel.GetDeclaredSymbol(typeSyntax) is not INamedTypeSymbol typeSymbol)
                continue;

            if (typeSyntax.Modifiers.All(m => m.ValueText != "partial"))
            {
                var diag = Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "TM001",
                        "ToggleMeshContext must be partial",
                        $"The type '{typeSymbol.Name}' must be declared as partial to use [ToggleMeshContext]",
                        "SourceGenerator",
                        DiagnosticSeverity.Error,
                        true),
                    typeSyntax.GetLocation());
                context.ReportDiagnostic(diag);
                continue;
            }

            var source = GenerateCode(typeSymbol);
            context.AddSource($"{typeSymbol.Name}_ContextAccessor.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string GenerateCode(INamedTypeSymbol typeSymbol)
    {
        var sb = new StringBuilder();
            
        var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace ? null : typeSymbol.ContainingNamespace.ToDisplayString();
            
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using ToggleMesh.Common.Contexts;");
        sb.AppendLine();
            
        if (ns != null)
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        var typeKeyword = typeSymbol.IsValueType ? "struct" : "class";
        var indentation = ns != null ? "    " : "";
            
        sb.AppendLine($"{indentation}partial {typeKeyword} {typeSymbol.Name} : IContextAccessor");
        sb.AppendLine($"{indentation}{{");
        sb.AppendLine($"{indentation}    public bool TryGetValue(string key, out string value)");
        sb.AppendLine($"{indentation}    {{");

        var properties = typeSymbol.GetMembers().OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && p is { IsStatic: false, GetMethod: not null })
            .ToList();

        var isFirst = true;
        foreach (var prop in properties)
        {
            var keyword = isFirst ? "if" : "else if";
            sb.AppendLine($"{indentation}        {keyword} (string.Equals(key, \"{prop.Name}\", StringComparison.OrdinalIgnoreCase))");
            sb.AppendLine($"{indentation}        {{");
                
            var type = prop.Type;
            if (type.SpecialType == SpecialType.System_String)
            {
                sb.AppendLine($"{indentation}            value = this.{prop.Name};");
                sb.AppendLine($"{indentation}            return value != null;");
            }
            else if (type.IsValueType)
            {
                if (type.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
                {
                    sb.AppendLine($"{indentation}            if (this.{prop.Name}.HasValue)");
                    sb.AppendLine($"{indentation}            {{");
                    sb.AppendLine($"{indentation}                value = this.{prop.Name}.Value.ToString();");
                    sb.AppendLine($"{indentation}                return true;");
                    sb.AppendLine($"{indentation}            }}");
                    sb.AppendLine($"{indentation}            value = null;");
                    sb.AppendLine($"{indentation}            return false;");
                }
                else
                {
                    sb.AppendLine($"{indentation}            value = this.{prop.Name}.ToString();");
                    sb.AppendLine($"{indentation}            return true;");
                }
            }
            else
            {
                sb.AppendLine($"{indentation}            value = this.{prop.Name}?.ToString();");
                sb.AppendLine($"{indentation}            return value != null;");
            }

            sb.AppendLine($"{indentation}        }}");
            isFirst = false;
        }

        sb.AppendLine($"{indentation}        value = null;");
        sb.AppendLine($"{indentation}        return false;");
        sb.AppendLine($"{indentation}    }}");
        sb.AppendLine($"{indentation}}}");

        if (ns != null)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }
}